---
version: '3.8'
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    volumes:
      - uptime-kuma:/app/data
    ports:
      - "127.0.0.1:3001:3001"
  nginx:
    image: nginx:latest
    container_name: nginx-reverse
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/my-site.com.crt:/etc/nginx/my-site.com.crt
      - ./nginx/my-site.com.key:/etc/nginx/my-site.com.key
    depends_on:
      - uptime-kuma
    ports:
      - "192.168.29.44:443:443"
networks:
  default:
    driver: bridge
    name: uptimenet
volumes:
  uptime-kuma:
    external: true
...
